import { Platform, StyleSheet } from 'react-native';
import Colors from './Colors';
import Constants from './Constants';

export default StyleSheet.create({
  wellcomeBox: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wellcomeText: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
    fontSize: Constants.FontSize.s12,
    fontWeight: 'bold',
  },
  wellcomeIcon: {
    marginBottom: 20,
    opacity: 0.8,
  },
  wellcomeButton: {
    backgroundColor: '#1C0056',
  },
  tabBarContainerFake: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  tabBarContainer: {
    height: Constants.MeasureSize(61.5),
    backgroundColor: Colors.tabNaviColor,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: Platform.OS === 'ios' ? 4 : 7 },
    shadowOpacity: Platform.OS === 'ios' ? 0.4 : 4,
    shadowRadius: Platform.OS === 'ios' ? 5 : 10,
    elevation: Platform.OS === 'ios' ? 5 : 8,
  },

  tabBarNotchContainer: {
    height: Constants.MeasureSize(55.5) + 20 + 4,
    borderTopWidth: 0.2,
    borderColor: Colors.tabNaviBorderColor,
    backgroundColor: Colors.tabNaviColor,
  },

  tabBarContent: {
    flexDirection: 'row',
    height: Constants.MeasureSize(55.5),
  },
  tabBarButton: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'center',
    height: Constants.MeasureSize(55.5),
    paddingTop: Constants.MeasureSize(5),
    // backgroundColor: Colors.white,
  },
  tabBarButtonHome: {
    justifyContent: 'center',
    alignItems: 'center',
    height: Constants.MeasureSize(80),
    width: Constants.MeasureSize(80),
    borderRadius: Constants.MeasureSize(60),
    bottom: 30,
    marginLeft: Constants.MeasureSize(10),
    marginRight: Constants.MeasureSize(10),
  },
  tabBarTopContentHighlightDot: {
    width: Constants.MeasureSize(10),
    height: Constants.MeasureSize(10),
    position: 'absolute',
    left: Constants.MeasureSize(7),
    top: Constants.MeasureSize(5),
    borderRadius: Constants.MeasureSize(10),
    backgroundColor: Colors.rubyRed,
  },
  tabBarTopContainer: {
    height: Constants.MeasureSize(52),
    width: Constants.ScreenSize.width,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'center',
    paddingBottom: Constants.MeasureSize(11),
  },
  tabBarTopContent: {
    flexDirection: 'row',
    height: Constants.MeasureSize(52),
    marginHorizontal: Constants.MeasureSize(5),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tabBarTopButton: {
    flex: 1,
    justifyContent: 'center',
    height: Constants.MeasureSize(34),
    backgroundColor: Colors.mainColor100,
    borderRadius: Constants.MeasureSize(100),
    paddingHorizontal: Constants.MeasureSize(14),
    marginHorizontal: Constants.MeasureSize(5),
    alignItems: 'center',
  },
  tabBarTopButtonTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  viewTabBar: {
    width: '100%',
    height: Constants.MeasureSize(32),
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabBarTopCountNotiContainer: {
    marginLeft: Constants.MeasureSize(5),
    borderRadius: Constants.MeasureSize(19),
    alignItems: 'center',
    justifyContent: 'center',
    width: Constants.MeasureSize(18),
    height: Constants.MeasureSize(18),
  },
  tabBarTopBottomLine: {
    height: Constants.MeasureSize(3),
    backgroundColor: Colors.Primary,
    top: Constants.MeasureSize(14),
    width: '100%',
  },
  tabBarTopButtonHome: {
    justifyContent: 'center',
    alignItems: 'center',
    height: Constants.MeasureSize(80),
    width: Constants.MeasureSize(80),
    borderRadius: Constants.MeasureSize(60),
    bottom: 30,
    marginLeft: Constants.MeasureSize(10),
    marginRight: Constants.MeasureSize(10),
    flex: 1,
  },
  button: {
    width: Constants.ScreenSize.width - 32,
    height: Constants.MeasureSize(42),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.Primary,
  },
  buttonOutLine: {
    width: Constants.ScreenSize.width - 32,
    height: Constants.MeasureSize(42),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.colorF1F8FF,
  },
  dotNotify: {
    width: Constants.MeasureSize(6),
    height: Constants.MeasureSize(6),
    borderRadius: Constants.MeasureSize(6),
    backgroundColor: Colors.red,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: Constants.MeasureSize(28),
    top: Constants.MeasureSize(8),
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerContentAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s14,
    color: Colors.buttonText,
    lineHeight: Constants.FontSize.s14 * (Constants.IS_IOS ? 1.4 : 1.5),
  },
  hyperLink: {
    width: 'auto',
    // height: Constants.MeasureSize(40),
    justifyContent: 'center',
    alignItems: 'center',
    // marginTop: Constants.MeasureSize(20),
    borderRadius: Constants.MeasureSize(8),
  },
  hyperLinkText: {
    textAlign: 'center',
    fontSize: Constants.FontSize.s13,
    color: Colors.hyperLinkText,
    textDecorationLine: 'underline',
  },
  shadowSmallLight: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  shadowCategoryMap: {
    shadowColor: '#484242',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  shadowButtonPlan: {
    shadowColor: '#484242',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 2,
  },
  shadowSmall: {
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  shadowSmallTop: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.16,
    shadowRadius: 2,
    elevation: 2,
  },
  shadowSmallSearch: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 5,
    elevation: 2,
  },
  shadowBottomSheet: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 7,
    elevation: 2,
  },
  shadowMedium: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  shadowProp: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  gravityCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  fontArial: {
    fontFamily: 'Arial',
  },
  viewButtonAdd: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  tabBarButtonAdd: {
    flex: 1,
    position: 'absolute',
    top: Constants.MeasureSize(-33),
    width: Constants.MeasureSize(50),
    height: Constants.MeasureSize(50),
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.MeasureSize(1),
  },

  tabBarButtonAddBot: {
    flex: 1,
    position: 'absolute',
    width: Constants.MeasureSize(50),
    height: Constants.MeasureSize(50),
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.MeasureSize(1),
  },

  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  overlayColor: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(16, 23, 32, 0.8)',
    zIndex: 1000,
  },

  shadowBigLight: {
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  fontBold: {
    fontFamily: Constants.FONTS?.BOLD,
  },
  fontSemiBold: {
    fontFamily: Constants.FONTS?.SEMI_BOLD,
  },
  fontMedium: {
    fontFamily: Constants.FONTS?.MEDIUM,
  },
  fontRegular: {
    fontFamily: Constants.FONTS?.REGULAR,
  },
  textFontSize7: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s7,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s7 * (Constants.IS_IOS ? 1.3 : 1.4),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize8: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s8,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s8 * (Constants.IS_IOS ? 1.3 : 1.4),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize10: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s10,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s10 * (Constants.IS_IOS ? 1.3 : 1.4),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize11: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s11,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s11 * (Constants.IS_IOS ? 1.3 : 1.4),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize12: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s12,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s12 * (Constants.IS_IOS ? 1.4 : 1.5),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize13: {
    fontWeight: '400',
    fontSize: Constants.FontSize.s13,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s13 * (Constants.IS_IOS ? 1.3 : 1.5),
    ...(Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) }),
  },
  textFontSize14: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s14,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s14 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize15: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s15,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s15 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize16: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s16,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s16 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize18: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s18,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s18 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize20: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s20,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s20 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize22: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s22,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s22 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize24: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s24,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s24 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize28: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s28,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s28 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textFontSize32: {
    fontWeight: '500',
    fontSize: Constants.FontSize.s32,
    color: Colors.gray900,
    lineHeight: Constants.FontSize.s32 * (Constants.IS_IOS ? 1.5 : 1.6),
    ...Constants.IS_ANDROID && { textAlignVertical: 'center', includeFontPadding: false, paddingVertical: Constants.MeasureSize(2) },
  },
  textWeightBold: {
    fontWeight: 'bold',
  },
  textWeight400: {
    fontWeight: '400',
  },
  textWeight500: {
    fontWeight: '500',
  },
  textWeight600: {
    fontWeight: '600',
  },
});
